menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact us', url: '/contact'}

people:
- {name: 'Rohan Balakrishnan', title: 'Assistant Professor', department: 'Biological Sciences', institution: 'University of North Texas', institution_address: '1155 Union Cir, Denton, TX 76205'
, phone: '', email: 'rohan.balakrishnan@unt.edu', office: 'LIFE A359/LIFE A229', image: 'assets/img/Rohan Balakrishnan Photo.jpg', url: 'https://scholar.google.com/citations?user=-UC9vYoAAAAJ&hl=en'}
- {name: 'Archana Kumm', title: 'student', department: 'TAMS', institution: 'UNT'}
- {name: 'Srikar Putrevu', title: 'student', department: 'TAMS', institution: 'UNT'}
- {name: 'Dongyun Kim', title: 'student', department: 'TAMS', institution: 'UNT'}
- {name: 'Anika Mallela', title: 'student', department: 'TAMS', institution: 'UNT'}
- {name: 'Amaira Nagar', title: 'student', institution: 'UNT'}
- {name: 'Gabriel Matthew', title: 'student', institution: 'UNT'}


courses:
- {name: '<b>BIOL 2041-Microbiology:</b> Fall 2025', url: ''}
- {name: '<b>BIOL 4801-Microbial Genetics:</b> Spring 2025', url: ''}


contacts:
- {name: 'Dr. Rohan Balakrishnan', title: 'Assistant Professor', department: 'Biological Sciences', institution: 'University of North Texas', institution_address: '', phone: '', email: 'rohan.balakrishnan@unt.edu', office: 'LIFE A359/LIFE A229', image: 'assets/img/UNTLifeScience.jpg'}
